### PR TITLE
HttpClient Builder Style Configuration

### PR DESCRIPTION
**Pull request by dmnjohns**
Another option for HttpClient configuration. I'm not quite sure how to test this paradigm, though.

### CODE REVIEW

**Comment by dkowis** [comment]
So don't use "."'ed names for the http params in here. Use camelCase like the methods in the builder.

**Comment by dmnjohns** [comment]
Made that change.

So for supporting configuration that takes a collection, how should we handle that? Since Flume hands us a Map[String, String], it seems like we'll have to come up with a convention for collections so that we can parse the value.

**Comment by dkowis** [comment]
That's a good point. Space separated? Comma Separated? Pipe Separated? We know what kind of data goes in there, so just pick a thingy that fits.

**Comment by adrianjgeorge** [comment]
space seperated would be a mistake, because sometimes properties readers consider a space to be the end of the property, and we don't know which they are using under the covers.

**Comment by dkowis** [comment]
@adrianjgeorge Flume's properties reader? Probably comma separated then.

**Comment by dmnjohns** [comment]
Yup, I went with comma separated. Now I just have to figure out how to test the configuration of a HttpClient... :neutral_face:

**Comment by dmnjohns** [comment]
Alright, I think we're good to go?

**Pull request merged**
